### ISSUE TITLE
Code smells found and refactoring with refactoring techniques.

### ISSUE THREAD

**Issue by willymateo** [BeanedTaco/CoffeeShop#1]
<b>Switch statements.</b>
Inconveniente detectado.
En la clase RemoteComands, los métodos startMenu() y order() cuentan con una serie de sentencias if-else para presentar el menú de funciones que se pueden realizar en la aplicación, actuar dependiendo de la escogida por el usuario y presentar el menú de los tipos de comidas que se ofrece.

![image](https://user-images.githubusercontent.com/67135809/104859470-9e3c9600-58f3-11eb-8ffc-dfe3936028ae.png)
![image](https://user-images.githubusercontent.com/67135809/104859473-a1d01d00-58f3-11eb-8ca4-255d3037d6bc.png)
  
Técnica de refactorización utilizada.
	Move Method.
	Extract Method.

Beneficios de refactorizar.
Gracias a la técnica de refactorización utilizada, ahora la clase CoffeShop cuenta con métodos específicos y muchas funcionalidades fueron extraídas y movidas. Como es el caso de la interfaz PaymentMethod que ahora cuenta con métodos específicos para procesar métodos de pago o la clase Product que cuenta con toda la información necesaria de un producto. Con esta nueva estructura implementada cada vez que se requiera añadir un nuevo producto se lo hará primero creando una instancia de la clase Product y luego hacer uso del método addProduct de la clase CoffeShop.

![image](https://user-images.githubusercontent.com/67135809/104859479-b3b1c000-58f3-11eb-9161-492bc0e27ac4.png)
![image](https://user-images.githubusercontent.com/67135809/104859481-b9a7a100-58f3-11eb-99db-6cc46d82e399.png)
 

<b>Primitive Obsession.</b>
Inconveniente detectado.
La variable local Balance perteneciente al método main de la clase CoffeShop es de tipo arreglo de enteros, pero solo se utiliza el primer y único espacio de memoria de ese arreglo, por lo tanto, en esencia representa un valor entero de la cantidad de dinero en la cuenta de una persona. Al inicio siempre se inicializa con $0 pero para añadir dinero se hace uso del método addMoneyMenu() de la inner class RemoteCommands.
  
![image](https://user-images.githubusercontent.com/67135809/104859485-bf9d8200-58f3-11eb-869e-785a481c2ef4.png)
![image](https://user-images.githubusercontent.com/67135809/104859486-c3310900-58f3-11eb-983c-ef60faf66e37.png)

Técnica de refactorización utilizada.
	Replace Conditional with Polymorphism.

Beneficios de refactorizar.
Se creó la interfaz PaymentMethod con los métodos addFunds(double amount) , processPayment(double amount) y getDetails() que los implementa la clase CreditCard para realizarlos de la forma en que lo realiza ese tipo de método de pago, sin embargo, en un futuro cuando se desee implementar otro método de pago diferente no se va a tener que modificar otra clase, solo crear la clase de método de pago diferente y hacer que implemente los métodos de la interfaz PaymentMethod.

![image](https://user-images.githubusercontent.com/67135809/104859488-c7f5bd00-58f3-11eb-9123-ed2309669b06.png)
![image](https://user-images.githubusercontent.com/67135809/104859509-f8d5f200-58f3-11eb-9bec-90e05cbc918a.png)

<b>Divergent Changes.</b>
Inconveniente detectado.
Cuando se requiere añadir un nuevo producto a la lista de productos es necesario modificar el método order() de la inner class RemoteCommands. Dependiendo del producto seleccionado se resta el precio en alguna sentencia if, entonces se añade el nombre del producto en el mensaje presentado por pantalla y el precio en la sentencia if, es decir, es necesario modificar diferentes partes de una sola clase.

![image](https://user-images.githubusercontent.com/67135809/104859517-09866800-58f4-11eb-85fd-e2371347d0eb.png)

Técnica de refactorización utilizada.
Extract superclass.

Beneficios de refactorizar.
Fue necesario la creación de la clase Product con los campos de instancia como nombre y precio, con esto es sencilla la creación de nuevos productos mediante la instanciación de dicha clase sin modificar el código fuente de ninguna otra. Si se desea crear una familia de productos más específicos solo es necesario heredar de la clase Product y añadir los campos y métodos con funcionalidades más específicas.

![image](https://user-images.githubusercontent.com/67135809/104859541-2327af80-58f4-11eb-824c-c670807268b9.png)

**Comment by hyd3rs** [comment]
I don't speak Spanish, unfortunately, and personally--this is a first project of mine in Java, I don't really care about it. I used very inefficient methods in Java, but like I said, it's expected as this was literally my first time working with the langauge. I'll keep these in mind (especially the switch statements, that's very helpful to know that those exist in Java as I'm coming from JavaScript and I'm very used to using those in JS).

Thank you for your feedback but I'll be closing this issue for the reason "DNC, do not care", but like I said, I will keep these in mind for my future projects.

- Danny
